apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azuresignalroutput
spec:
  type: bindings.azure.signalr
  version: v1
  metadata:
  - name: connectionString
    value: Endpoint=https://signalr-negotiate;AccessKey=;Version=1.0;
  - name: hub 
    value: spinozahub
    