apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azuresignalroutput
spec:
  type: bindings.azure.signalr
  version: v1
  metadata:
  - name: connectionString
    value: Endpoint=http://host.docker.internal:8888;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;
    #value: Endpoint=https://spinozasignalr.service.signalr.net;AccessKey=PX2Iu99frJJAapzcp/qQSco3gF6rjdWrhqMisv4mTeI=;Version=1.0;
  - name: hub 
    value: spinozahub