name: Backend

on:
  push:
    branches: [ main ]
    paths:
      - backend/**

  pull_request:
    branches: [ main ]
    paths:
      - backend/**

jobs:
  build_and_test:
    name: Build and test
    runs-on: windows-latest
      
    steps:
    - uses: dapr/setup-dapr@v1
      name: install dapr
      id: install

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET SDK 6.0 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend

    - name: 'Install Cosmos Emulator'
      uses: southpolesteve/cosmos-emulator-github-action@v1
      
    - name: start Azurite
      shell: bash
      run: |
           npm install -g azurite
           mkdir azurite
           azurite  --silent --location azurite &
      
    - name: Build 
      run: dotnet build backend/SpinozaBackEnd.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test backend/SpinozaBackEnd.sln --no-restore --verbosity normal
    
    # - name: Start dapr apps
    #   shell: pwsh
    #   run: |
    #         $spinoza_root = $pwd.Path
    #         runner.bat
    #         cd backend/CatalogManager
    #         dotnet test . 
