name: Build & publish spinoza images
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./backend/Managers/CatalogManager/Dockerfile
            image: spinozaacr.azurecr.io/spinoza.backend.managers.catalogmanager
          - dockerfile: ./backend/Accessors/TestCatalogAccessor/Dockerfile
            image: spinozaacr.azurecr.io/spinoza.backend.accessors.testaccessor
          - dockerfile: ./backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Dockerfile
            image: spinozaacr.azurecr.io/spinoza.backend.accessors.qustionaccessor
          - dockerfile: ./backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Dockerfile
            image: spinozaacr.azurecr.io/spinoza.backend.accessors.tagaccessor
          - dockerfile: ./backend/Managers/SignalRConnectionSupport/Docker/Dockerfile
            image: spinozaacr.azurecr.io/spinoza.backend.signalr.negotiate

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: spinozaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./backend
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          