# This is a basic workflow to help you get started with Actions

name: Deployment Integration Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: Restore dependencies
      run: dotnet restore SpinozaBackEnd.sln
    - name: Build
      run: dotnet build --no-restore SpinozaBackEnd.sln
    - name: Test
      env: 
        SPINOZA_SIGNALR_URL: url
        SPINOZA_TEST_CATALOG_URL : url
      run: dotnet test --no-build --verbosity normal --configuration Debug IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/Spinoza.Backend.Managers.TestCatalog.Tests.csproj
